# Generated by Django 2.1.2 on 2019-12-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('User_Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Mobile', models.BigIntegerField()),
                ('Email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
