# Generated by Django 2.1.2 on 2019-12-12 18:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_feedbackdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'PYTHON'), ('Django', 'DJANGO'), ('Rest Api', 'REST API'), ('Mysql', 'MYSQL')], max_length=300)),
                ('trainer', multiselectfield.db.fields.MultiSelectField(choices=[('Ravi', 'RAVI'), ('Sai', 'SAI'), ('Hari', 'HARI')], max_length=300)),
                ('branches', multiselectfield.db.fields.MultiSelectField(choices=[('Hyd', 'HYDERABAD'), ('Pune', 'PUNE'), ('Chennai', 'CHENNAI')], max_length=300)),
                ('date', models.DateField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
