# Generated by Django 2.1.2 on 2019-12-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0003_contactdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('start_time', models.TimeField(max_length=100)),
                ('trainer_exp', models.CharField(max_length=50)),
            ],
        ),
    ]
